#ifndef ELTECAR_DATASERVER_INCLUDE_GENERAL_SHAREDMEMORY_MEMORY_INFO_H
#define ELTECAR_DATASERVER_INCLUDE_GENERAL_SHAREDMEMORY_MEMORY_INFO_H

struct __attribute__((packed)) MemoryInfo {
  int bufferNumber = 0;
  int bufferSize;
  int bufferNamesCount;
};

#endif // ELTECAR_DATASERVER_INCLUDE_GENERAL_SHAREDMEMORY_MEMORY_INFO_H
